[package]
name = "derive-fields"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0.112"

[dependencies]
convert_case = "0.8"
proc-macro2 = "1"
quote = "1"
syn = "2"
