[package]
name = "derive-fields"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dev-dependencies]
trybuild = "1.0.112"

[dependencies]
convert_case = "0.8.0"
proc-macro2 = "1.0.103"
quote = "1.0.41"
# syn = { version = "2.0.108", features = ["extra-traits"] }
syn = "2.0.108"
